/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Invoice } from "./types";

// Helpful pre-populated data for Dons Leather Atelier
export const INITIAL_INVOICES: Invoice[] = [
  {
    id: "dla-seed-1",
    invoiceNumber: "DLA-2026-0001",
    date: "2026-05-10",
    customerName: "Alexander Vance",
    customerPhone: "+94 77 123 4567",
    customerAddress: "Flat 4B, Signature Residencies, Colombo 03",
    productDescription: "Bespoke Full-Grain Leather Briefcase with Solid Brass Hardwares",
    leatherType: "Horween Chromexcel (Cowhide)",
    color: "English Tan",
    quantity: 1,
    unitPrice: 125000,
    totalAmount: 125000,
    advancePayment: 50000,
    balancePayment: 75000,
    paymentStatus: "Partially Paid",
    orderStatus: "In Production",
    specialNotes: "Include laser engraved initials 'A.V.' on the front flap under the clasp. Burnish edges to a dark brown mirror finish.",
    createdAt: "2026-05-10T09:30:00.000Z",
  },
  {
    id: "dla-seed-2",
    invoiceNumber: "DLA-2026-0002",
    date: "2026-05-20",
    customerName: "Isabella Perera",
    customerPhone: "+94 71 987 6543",
    customerAddress: "12/1 Temple Road, Negombo",
    productDescription: "Minimalist Saffiano Leather Tote Pack & Matching Cardholder",
    leatherType: "Saffiano Calfskin",
    color: "Midnight Blue",
    quantity: 1,
    unitPrice: 85000,
    totalAmount: 85000,
    advancePayment: 85000,
    balancePayment: 0,
    paymentStatus: "Paid",
    orderStatus: "Ready for Delivery",
    specialNotes: "Selected lightweight cream linen lining. Suture thread is royal blue to contrast subtly with Midnight Blue calfskin.",
    createdAt: "2026-05-20T14:45:00.000Z",
  },
  {
    id: "dla-seed-3",
    invoiceNumber: "DLA-2026-0003",
    date: "2026-05-28",
    customerName: "Rohan De Silva",
    customerPhone: "+94 75 444 8888",
    customerAddress: "54 Outer Circular Road, Galle",
    productDescription: "Classic Hand-Stitched Leather Shell Cordovan Bifold Wallet",
    leatherType: "Japanese Shinki Shell Cordovan",
    color: "Burgundy #8",
    quantity: 2,
    unitPrice: 45000,
    totalAmount: 90000,
    advancePayment: 30000,
    balancePayment: 60000,
    paymentStatus: "Partially Paid",
    orderStatus: "Materials Secured",
    specialNotes: "Wants premium hand stitching (saddle stitching) with gold colored wax thread. Custom rounded corners on corners.",
    createdAt: "2026-05-28T08:15:30.000Z",
  },
];
